export const ACTIVITY_EVENT_TYPES = new Set([
  "COMMUNICATION_QUEUED", "COMMUNICATION_SENT", "COMMUNICATION_FAILED",
  "CONVERSATION_PLANNED", "CONVERSATION_APPROVED",
  "REMINDER_PLANNED", "REMINDER_APPROVED",
  "MEAL_RECORDED", "MEAL_REVIEWED",
  "AUTOMATION_STARTED", "AUTOMATION_COMPLETED", "AUTOMATION_FAILED",
])

export const EVENT_LABELS: Record<string, string> = {
  COMMUNICATION_QUEUED: "Queued",
  COMMUNICATION_SENT: "Sent",
  COMMUNICATION_FAILED: "Failed",
  CONVERSATION_PLANNED: "Conversation planned",
  CONVERSATION_APPROVED: "Conversation approved",
  REMINDER_PLANNED: "Reminder planned",
  REMINDER_APPROVED: "Reminder approved",
  MEAL_RECORDED: "Meal recorded",
  MEAL_REVIEWED: "Meal reviewed",
  AUTOMATION_STARTED: "Automation started",
  AUTOMATION_COMPLETED: "Automation completed",
  AUTOMATION_FAILED: "Automation failed",
}
