import type { Database } from './supabase'

export type { Database }

// Table row types
export type Profile                    = Database['public']['Tables']['profiles']['Row']
export type TrainerClient              = Database['public']['Tables']['trainer_clients']['Row']
export type MealPlan                   = Database['public']['Tables']['meal_plans']['Row']
export type MealSlot                   = Database['public']['Tables']['meal_slots']['Row']
export type FoodLog                    = Database['public']['Tables']['food_logs']['Row']
export type VoiceNote                  = Database['public']['Tables']['voice_notes']['Row']
export type StrikeLog                  = Database['public']['Tables']['strike_log']['Row']
export type WeeklyReport               = Database['public']['Tables']['weekly_reports']['Row']
export type Subscription               = Database['public']['Tables']['subscriptions']['Row']
export type ClientSubscription         = Database['public']['Tables']['client_subscriptions']['Row']
export type UpiPayment                 = Database['public']['Tables']['upi_payments']['Row']
export type IncomingWebhookLog         = Database['public']['Tables']['incoming_webhook_logs']['Row']
export type ClientGoal                 = Database['public']['Tables']['client_goals']['Row']
export type ClientHealthProfile        = Database['public']['Tables']['client_health_profiles']['Row']
export type ClientWorkoutSchedule      = Database['public']['Tables']['client_workout_schedules']['Row']
export type ClientPreference           = Database['public']['Tables']['client_preferences']['Row']
export type ClientComplianceSnapshot   = Database['public']['Tables']['client_compliance_snapshots']['Row']
export type TrainerAutomation          = Database['public']['Tables']['trainer_automations']['Row']
export type CommunicationLog           = Database['public']['Tables']['communication_logs']['Row']
export type MonthlyReport              = Database['public']['Tables']['monthly_reports']['Row']
export type AuditLog                   = Database['public']['Tables']['audit_logs']['Row']
export type ClientLifecycle            = Database['public']['Tables']['client_lifecycle']['Row']
export type Plan                       = Database['public']['Tables']['plans']['Row']
export type Trainer                    = Database['public']['Tables']['trainers']['Row']
export type TrainerSubscription        = Database['public']['Tables']['trainer_subscriptions']['Row']
export type PaymentReview              = Database['public']['Tables']['payment_reviews']['Row']

// Insert types
export type InsertProfile              = Database['public']['Tables']['profiles']['Insert']
export type InsertMealPlan             = Database['public']['Tables']['meal_plans']['Insert']
export type InsertMealSlot             = Database['public']['Tables']['meal_slots']['Insert']
export type InsertFoodLog              = Database['public']['Tables']['food_logs']['Insert']
export type InsertVoiceNote            = Database['public']['Tables']['voice_notes']['Insert']
export type InsertStrikeLog            = Database['public']['Tables']['strike_log']['Insert']
export type InsertWeeklyReport         = Database['public']['Tables']['weekly_reports']['Insert']
export type InsertSubscription         = Database['public']['Tables']['subscriptions']['Insert']
export type InsertClientSubscription   = Database['public']['Tables']['client_subscriptions']['Insert']
export type InsertUpiPayment           = Database['public']['Tables']['upi_payments']['Insert']
export type InsertIncomingWebhookLog   = Database['public']['Tables']['incoming_webhook_logs']['Insert']
export type InsertClientGoal           = Database['public']['Tables']['client_goals']['Insert']
export type InsertClientHealthProfile  = Database['public']['Tables']['client_health_profiles']['Insert']
export type InsertClientWorkoutSchedule= Database['public']['Tables']['client_workout_schedules']['Insert']
export type InsertClientPreference     = Database['public']['Tables']['client_preferences']['Insert']
export type InsertClientComplianceSnapshot=Database['public']['Tables']['client_compliance_snapshots']['Insert']
export type InsertTrainerAutomation    = Database['public']['Tables']['trainer_automations']['Insert']
export type InsertCommunicationLog     = Database['public']['Tables']['communication_logs']['Insert']
export type InsertMonthlyReport        = Database['public']['Tables']['monthly_reports']['Insert']
export type InsertAuditLog             = Database['public']['Tables']['audit_logs']['Insert']
export type InsertClientLifecycle      = Database['public']['Tables']['client_lifecycle']['Insert']
export type InsertPlan                 = Database['public']['Tables']['plans']['Insert']
export type InsertTrainer              = Database['public']['Tables']['trainers']['Insert']
export type InsertTrainerSubscription  = Database['public']['Tables']['trainer_subscriptions']['Insert']
export type InsertPaymentReview        = Database['public']['Tables']['payment_reviews']['Insert']

// Update types
export type UpdateProfile             = Database['public']['Tables']['profiles']['Update']
export type UpdateMealPlan            = Database['public']['Tables']['meal_plans']['Update']
export type UpdateMealSlot            = Database['public']['Tables']['meal_slots']['Update']
export type UpdateFoodLog             = Database['public']['Tables']['food_logs']['Update']
export type UpdateVoiceNote           = Database['public']['Tables']['voice_notes']['Update']
export type UpdateStrikeLog           = Database['public']['Tables']['strike_log']['Update']
export type UpdateWeeklyReport        = Database['public']['Tables']['weekly_reports']['Update']
export type UpdateSubscription        = Database['public']['Tables']['subscriptions']['Update']
export type UpdateClientSubscription  = Database['public']['Tables']['client_subscriptions']['Update']
export type UpdateUpiPayment          = Database['public']['Tables']['upi_payments']['Update']
export type UpdateIncomingWebhookLog  = Database['public']['Tables']['incoming_webhook_logs']['Update']
export type UpdateClientGoal          = Database['public']['Tables']['client_goals']['Update']
export type UpdateClientHealthProfile = Database['public']['Tables']['client_health_profiles']['Update']
export type UpdateClientWorkoutSchedule=Database['public']['Tables']['client_workout_schedules']['Update']
export type UpdateClientPreference    = Database['public']['Tables']['client_preferences']['Update']
export type UpdateClientComplianceSnapshot=Database['public']['Tables']['client_compliance_snapshots']['Update']
export type UpdateTrainerAutomation   = Database['public']['Tables']['trainer_automations']['Update']
export type UpdateCommunicationLog    = Database['public']['Tables']['communication_logs']['Update']
export type UpdateMonthlyReport       = Database['public']['Tables']['monthly_reports']['Update']
export type UpdateAuditLog            = Database['public']['Tables']['audit_logs']['Update']
export type UpdateClientLifecycle     = Database['public']['Tables']['client_lifecycle']['Update']
export type UpdatePlan                = Database['public']['Tables']['plans']['Update']
export type UpdateTrainer             = Database['public']['Tables']['trainers']['Update']
export type UpdateTrainerSubscription = Database['public']['Tables']['trainer_subscriptions']['Update']
export type UpdatePaymentReview       = Database['public']['Tables']['payment_reviews']['Update']

// Enum types
export type PaymentStatusType    = Database['public']['Enums']['payment_status_type']
export type ProcessingStatusType = Database['public']['Enums']['processing_status_type']
export type RoleType             = Database['public']['Enums']['role_type']
